year: 2024
events:
  - name: "Mexico City Grand Prix"
    sessions: ["Q", "R"]
    drivers: ["VER", "NOR", "LEC"]
  - name: "Italian Grand Prix"
    sessions: ["Q", "R"]
    drivers: ["VER", "NOR", "LEC"]
  - name: "Singapore Grand Prix"
    sessions: ["Q", "R"]
    drivers: ["VER", "NOR", "LEC"]